// <auto-generated />
using InsuranceAppWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsuranceAppWebApi.Data.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    [Migration("20210827104113_manytomanysimple")]
    partial class manytomanysimple
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("InsuranceAppWebApi.Domain.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("InsuranceAppWebApi.Domain.InsuranceCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("InsuranceCompanies");
                });

            modelBuilder.Entity("InsuranceAppWebApi.Domain.Insuree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Insurees");
                });

            modelBuilder.Entity("InsuranceInsuree", b =>
                {
                    b.Property<int>("InsurancesId")
                        .HasColumnType("int");

                    b.Property<int>("InsureesId")
                        .HasColumnType("int");

                    b.HasKey("InsurancesId", "InsureesId");

                    b.HasIndex("InsureesId");

                    b.ToTable("InsuranceInsuree");
                });

            modelBuilder.Entity("InsuranceAppWebApi.Domain.InsuranceCompany", b =>
                {
                    b.HasOne("InsuranceAppWebApi.Domain.Insurance", "Insurance")
                        .WithMany("InsuranceCompanies")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("InsuranceInsuree", b =>
                {
                    b.HasOne("InsuranceAppWebApi.Domain.Insurance", null)
                        .WithMany()
                        .HasForeignKey("InsurancesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsuranceAppWebApi.Domain.Insuree", null)
                        .WithMany()
                        .HasForeignKey("InsureesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsuranceAppWebApi.Domain.Insurance", b =>
                {
                    b.Navigation("InsuranceCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
